### PR TITLE
Updated Dmf_VirtualEyeGaze to include additional fields

### PR DESCRIPTION
**Pull request by harishsk**
Updated Dmf_VirtualEyeGaze to include head position and head direction in the report

### CODE REVIEW

**Comment by samtertzakian** [comment]
Thank you for the fix. I will leave it to you to "Squash and merge". This fix will be included in the next Release during after the next merge.

**Comment by harishsk** [comment]
It looks like I don't have the write permissions to merge. Can you please help with that?

**Comment by samtertzakian** [comment]
Darn...I am not sure why that is. Microsoft recently made a change to all the Github repositories related to rights. I will have to investigate why that is. I will get back to you about that. Sorry for the trouble. I know others have had similar issues.

For now, let me see if I can "Squash and merge" it for you.

**Comment by samtertzakian** [comment]
OK, I was able to merge it for you. It is possible that MSFT implemented a rule where only an employee can actually merge. I don't know, but I will try to find out and let you know.

**Pull request merged**
